package com.webService.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.0
//
// Created by Quasar Development at 18/07/2016
//
//---------------------------------------------------



public interface RTWIServiceEvents
{
    public void Starting();
    public void Completed(RTWOperationResult result);
}
